version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  nginx:
    image: bruno/yausc
    restart: always
    labels:
      - 'traefik.enable=true'
      - traefik.frontend.rule=Host:yausc.xyz
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - internal
      - web
